### ISSUE TITLE
Leverage new page move hooks 

### ISSUE THREAD

**Issue by hakjoon** [themotleyfool/wagtail-automatic-redirects#6]
Wagtail now has [page move hooks](https://docs.wagtail.io/en/stable/reference/hooks.html#after-move-page) that could be nice for adding redirects when moving a page that is already published.

**Comment by marteinn** [comment]
@hakjoon Actually you cannot re-implement this library using the move hooks without losing functionality. Those are:

- The `after_move_page` hook does not detect slug changes
- The `after_move_page` hook triggers no matter if page is published or not (you need to add manual checks)
- The `after_move_page` hook only triggers when you move a page in the admin ui, so if you move a page programmatically through `page.move` the hook wont fire

If anyone is interested in how the end result would look like, I have forked this library and made an example: https://github.com/marteinn/wagtail-automatic-move-redirects/blob/master/wagtail_automatic_redirects/wagtail_hooks.py

**Comment by ababic** [comment]
@hakjoon @marteinn might be worth considering the `pre_page_move` and `post_page_move` signals for this instead. These ARE fired for programmatic page moves, and give you a little bit more information to go on:

https://docs.wagtail.io/en/stable/reference/signals.html#pre-page-move-and-post-page-move
