### ISSUE TITLE
Update `SiteMiddleware` import for Wagtail 2.11 compat

### ISSUE THREAD

**Issue by tbrlpld** [themotleyfool/wagtail-automatic-redirects#8]
The import location of `SiteMiddleware` was changed in the 2.11 release of Wagtail to `wagtail.contrib.legacy`. The import would need to be changed in this package or the use of `SiteMiddleware` would need to be removed to allow use/development of the package with later versions of Wagtail. 

See also [Wagtail 2.11 release notes](https://docs.wagtail.io/en/stable/releases/2.11.html#sitemiddleware-moved-to-wagtail-contrib-legacy)

**Comment by tbrlpld** [comment]
Also wondering, is this added to the `MIDDLEWARES` list on purpose or is this just a default added by an older Wagtail starter? I did not find any use of `request.site` in the test app.

In that case, the reference could just be removed from the  `MIDDLEWARES` list.

**Comment by adamghill** [comment]
I removed that middleware because I don't think it was used in the test app -- thanks for bringing it up!
